zad_91
nescomtm/zad_9 pull request #1
Opened 2017-05-04 07:31 UTC by nescomtm

nowy pull reqeat do zadania 91

2017-05-04 15:54 UTC, zdolny requested changes

2017-05-04 15:54 UTC, zdolny commented on zad_91/js/scripts.js
> +var wynik = 0;
deklarowanie zmiennych jest tutaj niepotrzebne - wszystko, co powyzej mozesz usunac

2017-05-04 15:54 UTC, zdolny commented on zad_91/js/scripts.js
> +    }
wszystkie te ify i elsy polacz tak, abys mial tylko jeden warunek `if`, ktory sprawdza, czy `a` jest mniejsze rowne 0 lub `h` jest mniejsze rowne zero. Za tym ifem bedziesz mial jeden `else`, ktory bedzie zwracal wynik dzialania.

Nieprawidłowe razem ;)

2017-05-04 15:54 UTC, zdolny commented on zad_91/js/scripts.js
> +
brakuje testowego przypisania wywolan funkcji z roznymi parametrami do zmiennych, czyli np:
var triangle1Area = getTriangleArea(10, 15);

2017-05-04 15:54 UTC, zdolny commented on zad_91/js/scripts.js
> +    return wynik;
jesli dane sa nieprawidlowe, to nie wyswietlaj wyniku

2017-05-05 10:31 UTC, nescomtm commented
naniosłem poprawki

2017-05-05 15:57 UTC, zdolny commented
poprawilem orta i jest ok

2017-05-05 15:57 UTC, merged