zad_94
nescomtm/zad_9 pull request #4
Opened 2017-05-04 07:35 UTC by nescomtm

pull do zad 94

2017-05-04 18:39 UTC, zdolny requested changes

2017-05-04 18:39 UTC, zdolny commented on zad_94/js/scripts.js
> +var poziomy = 0;
ta deklaracja jest niepotrzebna

2017-05-04 18:39 UTC, zdolny commented on zad_94/js/scripts.js
> +var pion1 = '.';
te deklaracje tez do usuniecia

2017-05-04 18:39 UTC, zdolny commented on zad_94/js/scripts.js
> +    }
Caly ten blok if/else jest zbedny, sprobuj rozwiazac zadanie za pomoca 3 petli `for`.
Kropki niech beda spacjami i mozesz wyswietlac je w petli for

2017-05-05 10:44 UTC, nescomtm commented on zad_94/js/scripts.js
> +var poziomy = 0;
skasowane

2017-05-05 10:45 UTC, nescomtm commented on zad_94/js/scripts.js
> +var pion1 = '.';
jak usunę var pion1
to ma bład
scripts.js:33 Uncaught ReferenceError: pion1 is not defined
    at drawTree1 (scripts.js:33)
    at scripts.js:50

2017-05-05 16:28 UTC, zdolny commented on zad_94/js/scripts.js
> +var pion1 = '.';
tak, ten pion1 nie powinien byc Ci potrzebny jesli przerobisz kod na petle, ktore beda dzialac w ten sposob:
- zewnetrzna idzie po poziomach
- wewnetrzna 1 dodaje spacje
- wewnetrzna 2 dodaje czesci choinki

2017-05-05 20:49 UTC, nescomtm commented
zmieniłem , faktycznie lepiej , o tych trzech pętlach nie pomyślałem

2017-05-06 13:18 UTC, zdolny requested changes
tak informacyjnie: zmienne w js maja zasieg funkcyjny wiec nie musisz dla funkcji drawTree1 nazywac zmiennych typu star1, poziomy1...). Moga miec nazwy identyczne jak w funkcji drawTree

2017-05-06 13:18 UTC, zdolny commented on zad_94/js/scripts.js
> +    poziomy2 = poziomy1-1;
zmienna `poziomy2` jest zadeklarowana bez slowa kluczowego `var`, czyli niepotrzebnie staje sie zmienna globalna

2017-05-06 13:18 UTC, zdolny commented on zad_94/js/scripts.js
> +        console.log(pion1+star1);
prosciej bedzie korzystac tylko z jednej zmiennej np `star` i do niej dodawac zarowno spacje jak i znaki x, zamiast stosowac do tego 2 zmienne (pion1, star1)

2017-05-06 13:18 UTC, zdolny commented on zad_94/js/scripts.js
> +        dlugoscPion = pion1.length;
zmienna dlugoscPion jest zadeklarowana bez slowa kluczowego var, czyli niepotrzebnie staje sie zmienna globalna

2017-05-06 18:23 UTC, nescomtm commented on zad_94/js/scripts.js
> +        console.log(pion1+star1);
ale jak sa dwie zmienne to jest czytelniej , ale czy to jest taki wielki bład jak sie stosuje dwie zmienne,

2017-05-06 18:24 UTC, nescomtm commented on zad_94/js/scripts.js
> +    poziomy2 = poziomy1-1;
dodałem var do zmiennych aby były lokalne a nie globalne, fakt o tym nie pomyślałem

2017-05-07 17:47 UTC, zdolny commented on zad_94/js/scripts.js
> +        console.log(pion1+star1);
jesli jest to dla Ciebie czytelniejsze to ok, niech tak zostanie. 
Czesto po prostu mnozenie zmiennych prowadzi jednak to wiekszego zagmatwania niz czytelnosci - zostawiam to info na przyszlosc

2017-05-07 17:47 UTC, merged