zad_96
nescomtm/zad_9 pull request #6
Opened 2017-05-04 07:36 UTC by nescomtm

pull do zad 96

2017-05-04 18:57 UTC, zdolny requested changes

2017-05-04 18:57 UTC, zdolny commented on zad_96/js/scripts.js
> +    list.innerHTML += '<li>item '+liczba+'</li>';
dla przejrzystosci prosze abys ujednolicil spacje, czyli dodal je na okolo plusow przy zmiennej `liczba`

2017-05-04 18:57 UTC, zdolny commented on zad_96/js/scripts.js
> +console.log(add);
console.logi nie sa potrzebne - dobra praktyka jest czyszczenie console.logow uzywanych przy debugowaniu

2017-05-05 21:02 UTC, nescomtm commented
zmiany naniesione

2017-05-06 13:34 UTC, merged