zad_97
nescomtm/zad_9 pull request #7
Opened 2017-05-04 07:37 UTC by nescomtm

pull do zad 97

2017-05-04 18:53 UTC, zdolny requested changes
- [ ] prosze abys skorygowal/ujednolicil wciecia w html i js
- [ ] jesli gra jest po polsku, to niech wszystkie komunikaty wyswietlaja sie po polsku
- [ ] po zakonczeniu gry zlikwiduj ten alert, ktory mowi "Nacisnij OK aby rozpocząć gre od nowa". Zamiast tego powinno byc wyswietlone to co na poczatku gry, z buttonem 'Jeszcze raz' zgodnie ze stanem gry `ended`

2017-05-07 18:03 UTC, zdolny requested changes

2017-05-07 18:03 UTC, zdolny commented on zad_97/js/scripts.js
> +        var opoznienie = setTimeout(alert(playerResultElem.innerHTML),4000);
dlaczego to opoznienie?

2017-05-07 18:03 UTC, zdolny commented on zad_97/js/scripts.js
> +        var opoznienie = setTimeout(alert(computerResultElem.innerHTML),4000);
dlaczego to opoznienie?

2017-05-07 18:09 UTC, nescomtm commented on zad_97/js/scripts.js
> +        var opoznienie = setTimeout(alert(computerResultElem.innerHTML),4000);
koncepcja sie zmieniła a ja nie usunąłem tego

2017-05-07 18:10 UTC, nescomtm commented on zad_97/js/scripts.js
> +        var opoznienie = setTimeout(alert(computerResultElem.innerHTML),4000);
juz to wywaliłem z kodu

2017-05-07 18:11 UTC, nescomtm commented on zad_97/js/scripts.js
> +        var opoznienie = setTimeout(alert(computerResultElem.innerHTML),4000);
czy coś jeszcze jest źle?

2017-05-07 20:45 UTC, zdolny commented on zad_97/js/scripts.js
> +        var opoznienie = setTimeout(alert(computerResultElem.innerHTML),4000);
reszta ok :)

2017-05-07 20:45 UTC, merged